const express = require('express')
const router = express.Router()
const ManajemenUserCtrl = require('../controllers/manajemenUserDashboardCtrl')

router.get('/listSekolahTerdaftar', ManajemenUserCtrl.listSekolahTerdaftar)
router.get('/satuSekolahTerdaftar', ManajemenUserCtrl.satuSekolahTerdaftar)
router.put('/ubahSatuSekolahTerdaftar', ManajemenUserCtrl.ubahSatuSekolahTerdaftar)
router.get('/listAdministratorSatuSekolahTerdaftar', ManajemenUserCtrl.listAdministratorSatuSekolahTerdaftar)
router.get('/listSiswaSatuSekolahTerdaftar', ManajemenUserCtrl.listSiswaSatuSekolahTerdaftar)
router.get('/listStaffSatuSekolahTerdaftar', ManajemenUserCtrl.listStaffSatuSekolahTerdaftar)
router.post('/tambahStaffSatuSekolahTerdaftar', ManajemenUserCtrl.tambahStaffSatuSekolahTerdaftar)
router.get('/satuStaffSatuSekolahTerdaftar', ManajemenUserCtrl.satuStaffSatuSekolahTerdaftar)
router.put('/ubahStaffSatuSekolahTerdaftar', ManajemenUserCtrl.ubahStaffSatuSekolahTerdaftar)
router.post('/tambahSiswaSatuSekolahTerdaftar', ManajemenUserCtrl.tambahSiswaSatuSekolahTerdaftar)
router.get('/satuSiswaSatuSekolahTerdaftar', ManajemenUserCtrl.satuSiswaSatuSekolahTerdaftar)
router.put('/ubahSiswaSatuSekolahTerdaftar', ManajemenUserCtrl.ubahSiswaSatuSekolahTerdaftar)
router.post('/tambahAdministratorSatuSekolahTerdaftar', ManajemenUserCtrl.tambahAdministratorSatuSekolahTerdaftar)
router.get('/listAdministratorTerdaftar', ManajemenUserCtrl.listAdministratorTerdaftar)
router.get('/satuAdministratorTerdaftar', ManajemenUserCtrl.satuAdministratorTerdaftar)
router.post('/tambahAdministratorBaru', ManajemenUserCtrl.tambahAdministratorBaru)
router.put('/updateSatuAdministrator', ManajemenUserCtrl.updateSatuAdministrator)
router.post('/tambahSekolahBaru', ManajemenUserCtrl.tambahSekolahBaru)
// router.post('/', ManajemenUserCtrl.create)
// router.get('/', ManajemenUserCtrl.read)

module.exports = router;
